
sonar.projectKey=IT15_INATO_POS
sonar.projectName=OOTD Point of Sale System
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_d6c141d68b74a9889ef78c4780fe0751ff6a9e38
